openapi: 3.0.3
info:
  title: QuickWiki API
  version: 1.0.0
  description: API for QuickWiki
tags:
  - name: ping
    description: 疎通確認
  - name: lecture
    description: 講習会情報
  - name: wiki
    description: sodanと備忘録
paths:
  /ping:
    get:
      tags:
        - ping
      summary: 疎通確認
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ping'
  /lecture/{lectureId}:
    get:
      tags:
        - lecture
      summary: 1つの講習会情報の概要の取得
      parameters:
        - name: lectureId
          in: path
          required: true
          schema:
            type: string
          description: 講習会ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lecture'
  /lecture/{lectureId}/content:
    get:
      tags:
        - lecture
      summary: 1つの講習会のコンテンツの取得
      parameters:
        - name: lectureId
          in: path
          required: true
          schema:
            type: string
          description: 講習会ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/lecture'
  /lecture/byFolder/id/{folderId}:
    get:
      tags:
        - lecture
      summary: フォルダに対応する講習会のリストを取得
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: integer
          description: フォルダID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lectureList'
  /lecture/byFolder/path:
    get:
      tags:
        - lecture
      summary: フォルダに対応する講習会のリストを取得
      parameters:
        - name: folderpath
          in: query
          required: true
          schema:
            type: string
          description: フォルダパス
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lectureList'
  /lecture/folder/{folderId}:
    get:
      tags:
        - lecture
      summary: 子フォルダのリストの取得
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
          description: フォルダID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/folderList'
  /wiki/search:
    get:
      tags:
        - wiki
      summary: sodanと備忘録の検索
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
          description: 検索キーワード
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiList'
  /wiki/tag/{tag}: 
    get:
      tags:
        - wiki
      summary: タグに対応するsodanと備忘録のリストを取得
      parameters:
        - name: tag
          in: path
          required: true
          schema:
            type: string
          description: タグ
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiList'
  /wiki/{wikiId}:
    get:
      tags:
        - wiki
      summary: 1つのsodan/備忘録の取得
      parameters:
        - name: wikiId
          in: path
          required: true
          schema:
            type: string
          description: wikiID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiContent'
  /memo:
    post:
      tags:
        - wiki
      summary: 備忘録の作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newMemo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiContent'
    patch:
      tags:
        - wiki
      summary: 備忘録の更新
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateMemo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiContent'
    delete:
      tags:
        - wiki
      summary: 備忘録の削除
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memoId:
                  type: string
                  example: 123
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiContent'
  /memo/user/{userId}: 
    get:
      tags:
        - wiki
      summary: ユーザーの備忘録の取得
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: ユーザーID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiList'
  /memo/user/{userId}/favorite:
    get:
      tags:
        - wiki
      summary: ユーザーのお気に入りの備忘録の取得
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: ユーザーID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiList'
                

components:
  schemas:
    ping:
      type: object
      properties:
        message:
          type: string
          example: Pong
    lecture:
      type: object
      properties:
        id:
          type: integer
          example: 123
        title:
          type: string
          example: Introduction to Computer Science
        content:
          type: string
          example: マークダウン形式 資料へのリンク
        folderpath:
          type: string
          example: /School/ComputerScience
    lectureList:
      type: array
      items:
        $ref: '#/components/schemas/lecture'
    wikiList:
      type: array
      items:
        $ref: '#/components/schemas/wikiContent'
    wikiContent:
      type: object
      properties:
        id:
          type: integer
          example: 123
        type:
          type: string
          example: sodan
        title:
          type: string
          example: Introduction to Computer Science
        content:
          type: string
          example: This is an introductory course to computer science
        createdAt:
          type: string
          example: 2021-01-01 00:00:00
        updatedAt:
          type: string
          example: 2021-01-01 00:00:00
        ownerTraqId:
          type: string
          example: kavos
        tags:
          type: array
          items:
            type: string
            example: ComputerScience
    folderList:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 123
          name:
            type: string
            example: ComputerScience
          isFolder:
            type: boolean
            example: true
    newMemo:
      type: object
      properties:
        title:
          type: string
          example: Introduction to Computer Science
        content:
          type: string
          example: This is an introductory course to computer science
        ownerTraqId:
          type: string
          example: kavos
    updateMemo:
      type: object
      properties:
        id:
          type: integer
          example: 123
        title:
          type: string
          example: Introduction to Computer Science
        content:
          type: string
          example: This is an introductory course to computer science
        ownerTraqId:
          type: string
          example: kavos