openapi: 3.0.3
info:
  title: QuickWiki API
  version: 1.0.0
  description: API for QuickWiki
paths:
  /ping:
    get:
      summary: 疎通確認
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ping'
  /lecture/{lectureId}:
    get:
      summary: 1つの講習会情報の概要の取得
      parameters:
        - name: lectureId
          in: path
          required: true
          schema:
            type: string
          description: 講習会ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lectureAbstract'
  /lecture/{lectureId}/content:
    get:
      summary: 1つの講習会のコンテンツの取得
      parameters:
        - name: lectureId
          in: path
          required: true
          schema:
            type: string
          description: 講習会ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/lectureContent'
  /lecture/folder/{folderpath}:
    get:
      summary: フォルダパスに対応する講習会のリストを取得
      parameters:
        - name: folderpath
          in: path
          required: true
          schema:
            type: string
          description: フォルダパス
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lectureList'
  /wiki/search:
    get:
      summary: sodanと備忘録の検索
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
          description: 検索キーワード
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiList'
  /wiki/tag/{tag}: 
    get:
      summary: タグに対応するsodanと備忘録のリストを取得
      parameters:
        - name: tag
          in: path
          required: true
          schema:
            type: string
          description: タグ
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiList'
  /sodan/{sodanId}:
    get:
      summary: 1つのsodanの取得
      parameters:
        - name: sodanId
          in: path
          required: true
          schema:
            type: string
          description: sodanID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sodan'
  /memo:
    post:
      summary: メモの作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Introduction to Computer Science
                content:
                  type: string
                  example: This is an introductory course to computer science
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sodan'
    patch:
      summary: メモの更新
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Introduction to Computer Science
                content:
                  type: string
                  example: This is an introductory course to computer science
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sodan'
    delete:
      summary: メモの削除
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memoId:
                  type: string
                  example: 123
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sodan'
  /memo/{memoId}:
    get:
      summary: 1つのメモの取得
      parameters:
        - name: memoId
          in: path
          required: true
          schema:
            type: string
          description: メモID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/memo'
  /memo/user/{userId}: 
    get:
      summary: ユーザーのメモの取得
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: ユーザーID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiList'
  /memo/user/{userId}/favorite:
    get:
      summary: ユーザーのお気に入りのメモの取得
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: ユーザーID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wikiList'
                

components:
  schemas:
    ping:
      type: object
      properties:
        message:
          type: string
          example: Pong
    lectureAbstract:
      type: object
      properties:
        id:
          type: string
          example: 123
        title:
          type: string
          example: Introduction to Computer Science
        description:
          type: string
          example: これはコンピュータサイエンスの入門コースです．
        folderpath:
          type: string
          example: /School/ComputerScience
    lectureContent:
      type: object
      properties:
        id:
          type: string
          example: 123
        title:
          type: string
          example: Introduction to Computer Science
        description:
          type: string
          example: これはコンピュータサイエンスの入門コースです．
        folderpath:
          type: string
          example: /School/ComputerScience
        content:
          type: string
          example: マークダウン形式のコンテンツ
    lectureList:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: 123
    wikiList:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: 123
          type:
            type: string
            example: sodan
    sodan:
      type: object
      properties:
        id:
          type: string
          example: 123
        type:
          type: string
          example: sodan
        title:
          type: string
          example: Introduction to Computer Science
        content:
          type: string
          example: This is an introductory course to computer science
        tags:
          type: array
          items:
            type: string
            example: ComputerScience
    memo: 
      type: object
      properties:
        id:
          type: string
          example: 123
        title:
          type: string
          example: Introduction to Computer Science
        content:
          type: string
          example: This is an introductory course to computer science
        ownerTraqId:
          type: string
          example: kavos
        createdAt:
          type: string
          example: 2021-09-01 00:00:00
        updatedAt:
          type: string
          example: 2021-09-01 00:00:00